

spring:
  datasource:
    name: test
    url: jdbc:mysql://47.99.103.238:3306/vpay?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: mvc
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 1
    host: 192.168.15.31
    #    timeout: 1000ms
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
#    password: mvc123$%^
  mvc:
    async:
      request-timeout: 100ms
  application:
    name: CONSUMER
  rocketmq:
    producer:
      group: cryptovault-service
    nameServer: localhost:9876
server:
  port: 10081
