spring:
  redis:
    database: 1
    host: 192.168.15.31
    timeout: 1000ms
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  thymeleaf:
    cache: false
  profiles:
    include: "mockjson"
  mvc:
    async:
      request-timeout: 10ms
  mail:
    host: smtp.qq.com
    username: 416350144@qq.com
    password: zczvgqonpvfcbghb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: APP

logging:
  level:
    org: info
    io.swagger.models.parameters.AbstractSerializableParameter: error

server:
  port: 10086
  tomcat:
    max-threads: 5000
    min-spare-threads: 1000
    max-connections: 5000
  connection-timeout: 1000ms

service:
  name: app
  expire: 604800000
  refresh: 604800000
  base64Secret: MDk4ZjZ1iY2Q0NjIxZDM6M2hZGU0ZTgzMjYyN2I0ZjY=

feign.hystrix.enabled: true

hystrix.command.default.execution:
  isolation:
    thread.timeoutInMilliseconds: 5000
  timeout.enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
#swaggermock.switchOn: true
#swaggermock.retry: 5000