spring:
    application:
        name: service-eureka

server:
    port: 8762

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
    server:
        enable-self-preservation: false
